CREATE TABLE xp_accounts
(
   indri_account_id       varchar(250),
   account_name           varchar(255),
   account_group          varchar(255),
   customer_id            varchar(255),
   external_account_id    varchar(255),
   external_account_name  varchar(255),
   active                 integer
);

CREATE TABLE xp_campaigns
(
   campaign_id          varchar(250),
   campaign_name        varchar(255),
   label1               varchar(255),
   label2               varchar(255),
   label3               varchar(255),
   indri_account_id     varchar(255),
   label_type           varchar(255),
   publisher            varchar(255),
   account_group_label  varchar(255),
   active_reporting     integer
);

CREATE TABLE xp_commissions
(
   commission        numeric(4,2),
   indri_account_id  varchar(250),
   publisher         varchar(50)
);

CREATE TABLE xp_customers
(
   customer_id             varchar(250),
   customer_name           varchar(255),
   external_customer_code  varchar(255),
   external_customer_name  varchar(255)
);

CREATE TABLE xp_publisher_data
(
   indri_account_id           varchar(250),
   publisher_name             varchar(255),
   publisher_account_info     varchar(65000),
   xplenty_master_template_id integer,
   xplenty_package_id         integer,
   xplenty_connection_id      integer,
   xplenty_package_data       varchar(65000),
   xplenty_connection_data    varchar(65000),
   disabled                   integer
);


CREATE TABLE adwords_xplenty
(
   customerid                         varchar(65535)    NOT NULL,
   campaignid                         varchar(65535)    NOT NULL,
   campaignname                       varchar(65535)    NOT NULL,
   clickassistedconversions           float8,
   clickassistedconversionvalue       float8,
   date                               timestamp         NOT NULL,
   impressionassistedconversions      float8,
   impressionassistedconversionvalue  float8,
   impressions                        integer,
   searchimpressionshare              float8,
   indri_account_id                   varchar(65535)    NOT NULL,
   assistedrow                        integer,
   accountcurrencycode                varchar(65535),
   adgroupid                          integer,
   adgroupname                        varchar(65535),
   adgroupstatus                      varchar(65535),
   adnetworktype1                     varchar(65535),
   adnetworktype2                     varchar(65535),
   approvalstatus                     varchar(65535),
   averagecpc                         float8,
   averagecpm                         float8,
   averageposition                    float8,
   campaignstatus                     varchar(65535),
   clickconversionrate                float8,
   clicks                             integer,
   conversionvalue                    float8,
   convertedclicks                    integer,
   cost                               float8,
   costperconvertedclick              float8,
   criteria                           varchar(65535),
   criteriatype                       varchar(65535),
   ctr                                float8,
   device                             varchar(65535),
   qualityscore                       float8,
   videoquartile100rate               varchar(65535),
   videoquartile25rate                varchar(65535),
   videoquartile50rate                varchar(65535),
   videoquartile75rate                varchar(65535),
   videoviewrate                      varchar(65535),
   videoviews                         integer,
   viewthroughconversions             float8,
   criterionid                        varchar(65535),
   budget                             varchar(65535),
   criteriontype                      varchar(65535),
   valueperconvertedclick             float8,
   accountdescriptivename             varchar(65535),
   conversions                        float8
);

CREATE TABLE bing_xplenty
(
   date                 timestamp,
   account_id           varchar(65535),
   account_name         varchar(65535),
   average_cpc          float8,
   average_cpm          float8,
   campaign_id          varchar(65535),
   campaign_name        varchar(65535),
   clicks               integer,
   conversion_rate      float8,
   conversions          float8,
   cost_per_assist      float8,
   cost_per_conversion  float8,
   ctr                  float8,
   currency_code        varchar(65535),
   impressions          integer,
   spend                float8,
   total_visits         integer,
   indri_account_id     varchar(65535)
);


CREATE TABLE creative_xplenty
(
   customerid              varchar(65535)    NOT NULL,
   accountcurrencycode     varchar(65535),
   adtype                  varchar(65535),
   averagecpc              float8,
   campaignid              integer           NOT NULL,
   campaignname            varchar(65535),
   clicks                  integer,
   cost                    float8,
   creativedestinationurl  varchar(65535),
   ctr                     float8,
   date                    timestamp         NOT NULL,
   description1            varchar(65535),
   description2            varchar(65535),
   displayurl              varchar(65535),
   headline                varchar(65535),
   imageadurl              varchar(65535),
   imagecreativename       varchar(65535),
   impressions             integer,
   indri_account_id        varchar(65535),
   publisher               varchar(65535),
   accountdescriptivename  varchar(65535)
);

CREATE TABLE facebook_agegender
(
   account_id                 varchar(65535)    NOT NULL,
   account_name               varchar(65535),
   campaign_id                varchar(65535)    NOT NULL,
   campaign_name              varchar(65535),
   ad_id                      varchar(65535),
   ad_name                    varchar(65535),
   buying_type                varchar(65535),
   adset_id                   varchar(65535),
   adset_name                 varchar(65535),
   objective                  varchar(65535),
   total_actions              integer,
   total_unique_actions       integer,
   action_values              varchar(65535),
   total_action_value         varchar(65535),
   social_impressions         varchar(65535),
   clicks                     integer,
   social_clicks              integer,
   unique_impressions         integer,
   unique_social_impressions  integer,
   frequency                  float8,
   reach                      integer,
   impressions                integer,
   unique_clicks              integer,
   inline_link_clicks         integer,
   website_clicks             integer,
   ctr                        float8,
   spend                      float8,
   cpm                        float8,
   cpc                        float8,
   cpp                        float8,
   date_start                 timestamp         NOT NULL,
   date_stop                  timestamp         NOT NULL,
   age                        varchar(65535)    NOT NULL,
   gender                     varchar(65535)    NOT NULL,
   indri_account_id           varchar(65535)    NOT NULL,
   action_likes               integer,
   action_link_click          integer,
   action_page_engagement     integer,
   action_post_engagement     integer,
   action_leadgen_other       integer,
   action_post_like           integer
);

CREATE TABLE facebook_region
(
   account_id                 varchar(65535)    NOT NULL,
   account_name               varchar(65535),
   campaign_id                varchar(65535)    NOT NULL,
   campaign_name              varchar(65535),
   ad_id                      varchar(65535),
   ad_name                    varchar(65535),
   buying_type                varchar(65535),
   adset_id                   varchar(65535),
   adset_name                 varchar(65535),
   objective                  varchar(65535),
   total_actions              integer,
   total_unique_actions       integer,
   action_values              varchar(65535),
   total_action_value         varchar(65535),
   social_impressions         varchar(65535),
   clicks                     integer,
   social_clicks              integer,
   unique_impressions         integer,
   unique_social_impressions  integer,
   frequency                  float8,
   reach                      integer,
   impressions                integer,
   unique_clicks              integer,
   inline_link_clicks         integer,
   website_clicks             integer,
   ctr                        float8,
   spend                      float8,
   cpm                        float8,
   cpc                        float8,
   cpp                        float8,
   date_start                 timestamp         NOT NULL,
   date_stop                  timestamp         NOT NULL,
   region                     varchar(65535)    NOT NULL,
   indri_account_id           varchar(65535),
   action_likes               integer,
   action_link_click          integer,
   action_page_engagement     integer,
   action_post_engagement     integer,
   action_leadgen_other       integer,
   action_post_like           integer
);

CREATE TABLE ganalytics_xplenty
(
   profileid              varchar(65535),
   accountname            varchar(65535),
   propertyname           varchar(65535),
   profilename            varchar(65535),
   ga_campaign            varchar(65535),
   ga_sourcemedium        varchar(65535),
   ga_keyword             varchar(65535),
   ga_adgroup             varchar(65535),
   ga_devicecategory      varchar(65535),
   ga_currencycode        varchar(65535),
   ga_date                timestamp,
   ga_users               integer,
   ga_percentnewsessions  float8,
   ga_sessions            integer,
   ga_bouncerate          float8,
   ga_avgsessionduration  float8,
   ga_pageviews           integer,
   ga_avgtimeonpage       varchar(65535),
   ga_transactions        integer,
   ga_transactionrevenue  float8,
   indri_account_id       varchar(65535)
);

CREATE TABLE tradedesk_xplenty
(
   date                            timestamp,
   partner_id                      varchar(65535)    NOT NULL,
   advertiser_id                   varchar(65535)    NOT NULL,
   campaign_id                     varchar(65535)    NOT NULL,
   ad_group_id                     varchar(65535),
   ad_format                       varchar(65535),
   creative_id                     varchar(65535),
   frequency                       integer,
   advertiser_name                 varchar(65535),
   campaign_name                   varchar(65535),
   ad_group_name                   varchar(65535),
   ad_group_budget                 float4,
   ad_group_imps_budget            varchar(65535),
   ad_group_daily_target           float4,
   ad_group_daily_imps_target      varchar(65535),
   ad_group_daily_cap              varchar(65535),
   ad_group_daily_imps_cap         varchar(65535),
   ad_group_base_bid_cpm           float4,
   creative_name                   varchar(65535),
   bids                            integer,
   bid_amount                      float4,
   imps                            integer,
   clicks                          integer,
   pc_1                            integer,
   pc_2                            integer,
   pc_3                            integer,
   pc_4                            integer,
   pc_5                            integer,
   pc_6                            integer,
   pi_1                            integer,
   pi_2                            integer,
   pi_3                            integer,
   pi_4                            integer,
   pi_5                            integer,
   pi_6                            integer,
   pc_1_rev                        float4,
   pc_2_rev                        float4,
   pc_3_rev                        float4,
   pc_4_rev                        float4,
   pc_5_rev                        float4,
   pc_6_rev                        float4,
   pi_1_rev                        float4,
   pi_2_rev                        float4,
   pi_3_rev                        float4,
   pi_4_rev                        float4,
   pi_5_rev                        float4,
   pi_6_rev                        float4,
   pc_1_cur                        varchar(65535),
   pc_2_cur                        varchar(65535),
   pc_3_cur                        varchar(65535),
   pc_4_cur                        varchar(65535),
   pc_5_cur                        varchar(65535),
   pc_6_cur                        varchar(65535),
   pi_1_cur                        varchar(65535),
   pi_2_cur                        varchar(65535),
   pi_3_cur                        varchar(65535),
   pi_4_cur                        varchar(65535),
   pi_5_cur                        varchar(65535),
   pi_6_cur                        varchar(65535),
   ttd_total_cost                  varchar(65535),
   partner_total_cost              varchar(65535),
   advertiser_total_cost           float4,
   videoeventcreativeview          integer,
   videoeventstart                 integer,
   videoeventfirstquarter          integer,
   videoeventmidpoint              integer,
   videoeventthirdquarter          integer,
   videoeventcomplete              integer,
   videoeventmute                  integer,
   videoeventunmute                integer,
   videoeventpause                 integer,
   videoeventresume                integer,
   videoeventfullscreen            integer,
   videoeventerror                 integer,
   videoeventskip                  integer,
   videoeventengagedview           integer,
   videoeventrewind                integer,
   videoeventexpand                integer,
   videoeventcollapse              integer,
   videoeventacceptinvitation      integer,
   videoeventclose                 integer,
   cta_1                           integer,
   cta_2                           integer,
   cta_3                           integer,
   cta_4                           integer,
   cta_5                           integer,
   cta_6                           integer,
   cta_1_rev                       float4,
   cta_2_rev                       float4,
   cta_3_rev                       float4,
   cta_4_rev                       float4,
   cta_5_rev                       float4,
   cta_6_rev                       float4,
   twd_1                           integer,
   twd_2                           integer,
   twd_3                           integer,
   twd_4                           integer,
   twd_5                           integer,
   twd_6                           integer,
   twd_1_rev                       float4,
   twd_2_rev                       float4,
   twd_3_rev                       float4,
   twd_4_rev                       float4,
   twd_5_rev                       float4,
   twd_6_rev                       float4,
   deal_code                       varchar(65535),
   adserver_name                   varchar(65535),
   adserver_creative_placement_id  varchar(65535),
   creativeistrackable             integer,
   creativewasviewable             integer,
   indri_account_id                varchar(255)
);

CREATE TABLE tradedesk_reportfiles
(
   downloadurlexpirationdateutc  varchar(65535),
   advertiserid                  varchar(65535),
   type                          varchar(65535),
   duration                      varchar(65535),
   downloadurl                   varchar(65535),
   scope                         varchar(65535),
   reportdateutc                 varchar(65535)
);



